// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSBaaWMF9Kz6Vtom5W6nWMhe07FikFevY',
    appId: '1:869603955109:web:20fc637d34834ab9ef984c',
    messagingSenderId: '869603955109',
    projectId: 'fb-todoos',
    authDomain: 'fb-todoos.firebaseapp.com',
    storageBucket: 'fb-todoos.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0LZOb4ZvFItzO4sWbc643ORmgKdOUXok',
    appId: '1:869603955109:android:17dfd194c1f15869ef984c',
    messagingSenderId: '869603955109',
    projectId: 'fb-todoos',
    storageBucket: 'fb-todoos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeJoDJwPjtybdiVIM_11MF-R5yRuFjAyg',
    appId: '1:869603955109:ios:8b409d8eff188837ef984c',
    messagingSenderId: '869603955109',
    projectId: 'fb-todoos',
    storageBucket: 'fb-todoos.appspot.com',
    iosBundleId: 'com.example.todoos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeJoDJwPjtybdiVIM_11MF-R5yRuFjAyg',
    appId: '1:869603955109:ios:8b409d8eff188837ef984c',
    messagingSenderId: '869603955109',
    projectId: 'fb-todoos',
    storageBucket: 'fb-todoos.appspot.com',
    iosBundleId: 'com.example.todoos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSBaaWMF9Kz6Vtom5W6nWMhe07FikFevY',
    appId: '1:869603955109:web:54e7bb6a0be98fa1ef984c',
    messagingSenderId: '869603955109',
    projectId: 'fb-todoos',
    authDomain: 'fb-todoos.firebaseapp.com',
    storageBucket: 'fb-todoos.appspot.com',
  );
}
